/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SchoolProfileRouteImport } from './routes/school-profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentSetupRouteImport } from './routes/student-setup'
import { Route as HomeworkIndexRouteImport } from './routes/homework/index'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as StudySubjectRouteImport } from './routes/study/$subject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolProfileRoute = SchoolProfileRouteImport.update({
  id: '/school-profile',
  path: '/school-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSetupRoute = StudentSetupRouteImport.update({
  id: '/student-setup',
  path: '/student-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkIndexRoute = HomeworkIndexRouteImport.update({
  id: '/homework/',
  path: '/homework/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySubjectRoute = StudySubjectRouteImport.update({
  id: '/study/$subject',
  path: '/study/$subject',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/school-profile': typeof SchoolProfileRoute
  '/signup': typeof SignupRoute
  '/student-setup': typeof StudentSetupRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/study/$subject': typeof StudySubjectRoute
  '/homework/': typeof HomeworkIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/school-profile': typeof SchoolProfileRoute
  '/signup': typeof SignupRoute
  '/student-setup': typeof StudentSetupRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/study/$subject': typeof StudySubjectRoute
  '/homework': typeof HomeworkIndexRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/school-profile': typeof SchoolProfileRoute
  '/signup': typeof SignupRoute
  '/student-setup': typeof StudentSetupRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/study/$subject': typeof StudySubjectRoute
  '/homework/': typeof HomeworkIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/school-profile'
    | '/signup'
    | '/student-setup'
    | '/lesson/$lessonId'
    | '/study/$subject'
    | '/homework/'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/school-profile'
    | '/signup'
    | '/student-setup'
    | '/lesson/$lessonId'
    | '/study/$subject'
    | '/homework'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/school-profile'
    | '/signup'
    | '/student-setup'
    | '/lesson/$lessonId'
    | '/study/$subject'
    | '/homework/'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SchoolProfileRoute: typeof SchoolProfileRoute
  SignupRoute: typeof SignupRoute
  StudentSetupRoute: typeof StudentSetupRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  StudySubjectRoute: typeof StudySubjectRoute
  HomeworkIndexRoute: typeof HomeworkIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-profile': {
      id: '/school-profile'
      path: '/school-profile'
      fullPath: '/school-profile'
      preLoaderRoute: typeof SchoolProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-setup': {
      id: '/student-setup'
      path: '/student-setup'
      fullPath: '/student-setup'
      preLoaderRoute: typeof StudentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework/': {
      id: '/homework/'
      path: '/homework'
      fullPath: '/homework/'
      preLoaderRoute: typeof HomeworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$subject': {
      id: '/study/$subject'
      path: '/study/$subject'
      fullPath: '/study/$subject'
      preLoaderRoute: typeof StudySubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SchoolProfileRoute: SchoolProfileRoute,
  SignupRoute: SignupRoute,
  StudentSetupRoute: StudentSetupRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  StudySubjectRoute: StudySubjectRoute,
  HomeworkIndexRoute: HomeworkIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
